### ISSUE TITLE
Mac OS artifact is not signed thus preventing application execution

### ISSUE THREAD

**Issue by mrfu2** [ndelvalle/nakatoshi#12]
MacOS artifacts from releases will not be opened by the Mac OS because the executable is not signed.
<img width="431" alt="image" src="https://user-images.githubusercontent.com/2567378/85183964-2ee3c280-b28e-11ea-9fec-66bd2a5aba06.png">

**Comment by ndelvalle** [comment]
Running 

```bash
$ xattr -d com.apple.quarantine ./nakatoshi-macos-amd64
```
Fix my issue, but of course is an ugly work around 😢

**Comment by ndelvalle** [comment]
Probably the best solution here is to add the bin to homebrew

**Comment by ndelvalle** [comment]
Nakatoshi now is on brew so this would be the preferred way to installed on MacOS. https://github.com/ndelvalle/nakatoshi/commit/dd65db729f4663936558358847a62321bd24aaea
