### ISSUE TITLE
Can't install via brew

### ISSUE THREAD

**Issue by mariodian** [ndelvalle/nakatoshi#210]
Hi, when I try to add the repository via `brew tap ndelvalle/utilities` I get the following error:

````
==> Tapping ndelvalle/utilities
Cloning into '/usr/local/Homebrew/Library/Taps/ndelvalle/homebrew-utilities'...
remote: Repository not found.
fatal: repository 'https://github.com/ndelvalle/homebrew-utilities/' not found
Error: Failure while executing; `git clone https://github.com/ndelvalle/homebrew-utilities /usr/local/Homebrew/Library/Taps/ndelvalle/homebrew-utilities --origin=origin --template=` exited with 128. 
````

Any way to fix this?

**Comment by ndelvalle** [comment]
Thanks for reporting @mariodian for some reason I made the repo private and forgot to make it public again, can you try again, it should work.

**Comment by ndelvalle** [comment]
I am going to close this issue, if you have any issues again, please re-open or create a new one.
